*Task 1*

In [65]:
import torch
import numpy as np
import random

In [2]:
c = np.ones((3,3))

In [3]:
d = torch.from_numpy(c)

In [18]:
d.shape

torch.Size([3, 3])

Task 2

参考: https://zh-v2.d2l.ai/chapter_linear-networks/linear-regression-scratch.html

In [119]:
x = torch.arange(0, 100, 1.0).reshape(-1, 1)
# x = torch.arange(0, 100, 0.01).reshape(-1, 1)
true_w = torch.tensor([10.0])
true_b = 5.0

y = torch.matmul(x, true_w) + true_b + torch.rand(len(x))
y = y.reshape((-1, 1))

print(y.shape)
print(y)

torch.Size([100, 1])
tensor([[  5.4486],
        [ 15.8055],
        [ 25.5127],
        [ 35.0496],
        [ 45.9990],
        [ 55.5986],
        [ 65.1468],
        [ 75.3579],
        [ 85.0197],
        [ 95.1428],
        [105.3848],
        [115.7627],
        [125.7779],
        [135.2398],
        [145.1631],
        [155.2390],
        [165.0650],
        [175.7670],
        [185.4457],
        [195.8557],
        [205.6063],
        [215.0379],
        [225.2259],
        [235.0730],
        [245.3627],
        [255.5756],
        [265.3289],
        [275.9504],
        [285.1467],
        [295.2461],
        [305.8420],
        [315.5922],
        [325.9077],
        [335.4059],
        [345.5045],
        [355.6310],
        [365.6233],
        [375.4219],
        [385.5858],
        [395.5213],
        [405.5627],
        [415.2932],
        [425.2245],
        [435.9653],
        [445.5191],
        [455.2238],
        [465.2867],
        [475.6849],
        [485.5094],

In [120]:
x[0], y[0]

(tensor([0.]), tensor([5.4486]))

In [63]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [123]:
batch_size = 10

for x_batch, y_batch in data_iter(batch_size, x, y):
    print(x_batch)
    # print(x_batch, '\n', y)
    break

tensor([[40.],
        [16.],
        [62.],
        [22.],
        [12.],
        [33.],
        [18.],
        [20.],
        [69.],
        [71.]])


In [124]:
def linreg(x, w, b):
    return torch.matmul(x, w) + b

In [125]:
def squared_loss(y_hat, y):
    return (y_hat - y.reshape(y_hat.shape)) ** 2 / 2

In [126]:
def sgd(params, lr, batch_size):
    """小批量随机梯度下降。"""
    with torch.no_grad():
        for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()

In [127]:
lr = 0.0001
num_epochs = 10
net = linreg
loss = squared_loss

batch_size = 10

w = torch.normal(0, 0.01, size=(1,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

for epoch in range(num_epochs):
    for x_batch, y_batch in data_iter(batch_size, x, y):
        z = net(x_batch, w, b)
        # print(z)
        l = loss(z, y_batch)  # `X`和`y`的小批量损失
        # 因为`l`形状是(`batch_size`, 1)，而不是一个标量。`l`中的所有元素被加到一起，
        # 并以此计算关于[`w`, `b`]的梯度
        l.sum().backward()
        sgd([w, b], lr, batch_size)  # 使用参数的梯度更新参数
        # print(w, b)
    with torch.no_grad():
        train_l = loss(net(x, w, b), y)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')
        print(f'w: {w}, b: {b}')

epoch 1, loss 47.715626
w: tensor([[9.9171]], requires_grad=True), b: tensor([0.1521], requires_grad=True)
epoch 2, loss 3.535384
w: tensor([[10.0816]], requires_grad=True), b: tensor([0.1560], requires_grad=True)
epoch 3, loss 3.552594
w: tensor([[10.0776]], requires_grad=True), b: tensor([0.1572], requires_grad=True)
epoch 4, loss 3.580731
w: tensor([[10.0865]], requires_grad=True), b: tensor([0.1587], requires_grad=True)
epoch 5, loss 3.530552
w: tensor([[10.0802]], requires_grad=True), b: tensor([0.1600], requires_grad=True)
epoch 6, loss 3.529698
w: tensor([[10.0799]], requires_grad=True), b: tensor([0.1613], requires_grad=True)
epoch 7, loss 3.539842
w: tensor([[10.0839]], requires_grad=True), b: tensor([0.1627], requires_grad=True)
epoch 8, loss 3.538150
w: tensor([[10.0839]], requires_grad=True), b: tensor([0.1640], requires_grad=True)
epoch 9, loss 3.524020
w: tensor([[10.0799]], requires_grad=True), b: tensor([0.1653], requires_grad=True)
epoch 10, loss 3.524725
w: tensor([[1